[tool.poetry]
name = "flask proj"
version = "0.1.0"
description = ""
authors = ["Vell1ngton <tema.mordvinov1@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
gunicorn = "^22.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
